name: OpenGui
version: '${project.version}'
main: nl.leobaehre.opengui.OpenGui
api-version: '1.20'
commands:
  opengui:
    description: Open a GUI
    usage: /<command> <gui>
  open:
    description: Open a GUI
    usage: /<command> <gui>